version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - run: |
            node --version
            java --version
            google-chrome --version
      - restore_cache:
          key: NodeModules-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Installing dependencies
          command: npm install
      - save_cache:
          key: NodeModules-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: Building
          command: npm run build
  test:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          key: NodeModules-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Installing dependencies
          command: npm install
      - save_cache:
          key: NodeModules-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: Running tests
          command: npm run test

workflows:
  build_and_test:
    jobs:
      - build
      - test
