version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

commands:
  checkout_and_install:
    steps:
      - checkout
      - restore_cache:
          key: NodeModules-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Installing dependencies
          command: npm install
      - save_cache:
          key: NodeModules-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"

jobs:
  lint:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout_and_install
      - run:
          name: Linting
          command: npm run lint:ci
      - store_test_results:
          path: ./reports/eslint
      - store_artifacts:
          path: ./reports/eslint

  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout_and_install
      - run:
          name: Building
          command: npm run build
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout_and_install
      - run:
          name: Running tests
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/jest
      - store_test_results:
         path: ./reports/jest
      - store_artifacts:
         path: ./reports/jest
      - store_artifacts:
         path: ./coverage
      - persist_to_workspace:
         root: /tmp/workspace
         paths:
           - ./coverage

  upload_coverage_to_coveralls:
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
         at: /tmp/workspace
      - coveralls/upload:
         path_to_lcov: /tmp/workspace/coverage/lcov.info

workflows:
  version: 2
  lint_test_build:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
      - upload_coverage_to_coveralls:
          requires:
            - test
